### ISSUE TITLE
Add theming for Vim Mode wrapper

### ISSUE THREAD

**Issue by TyceHerrman** [dracula/zed#25]
Now that https://github.com/zed-industries/zed/pull/39813 is merged, would be great to have the vim mode wrapper match the dracula theme.

**Comment by Otterpocket** [comment]
Yea feels like a solid change, I'll get to it soon 👍, thanks

**Comment by Bogdan-Torkhov** [comment]
@Otterpocket Very cool! How soon these feature will be added?

**Comment by Otterpocket** [comment]
https://github.com/zed-industries/extensions/pull/3767

<img width="778" height="335" alt="Image" src="https://github.com/user-attachments/assets/020cd4db-4490-4c6e-b06a-fbf751506e79" />

**Comment by Otterpocket** [comment]
resolved by https://github.com/zed-industries/extensions/pull/3767

**Comment by dudeperf3ct** [comment]
Hi @Otterpocket, thanks for awesome theme.

I was wondering if the vim mode wrapper are also added to Dracula Solid theme.

**Comment by Otterpocket** [comment]
> Hi [@Otterpocket](https://github.com/Otterpocket), thanks for awesome theme.
> 
> I was wondering if the vim mode wrapper are also added to Dracula Solid theme.

Thanks @dudeperf3ct, To be honest, I would have expected the solid theme to have automatically received the theme changes, but you are correct, the styles did not apply.
I'll include them in the next release.

Side Note: I'm assuming you use solid because of the issues with linux and transparency? I made some changes to the core theme that could make it less of an issue, I would be interested to know if the core theme still an issue for you ?

**Comment by dudeperf3ct** [comment]
Thanks @Otterpocket 

> Side Note: I'm assuming you use solid because of the issues with linux and transparency? I made some changes to the core theme that could make it less of an issue, I would be interested to know if the core theme still an issue for you ?

Yes, I was using the latest release and still facing the same issue transparency issue.

**Comment by dudeperf3ct** [comment]
@Otterpocket  I think the vim mode wrapper is still not included in the latest release.

https://github.com/dracula/zed/blob/08a007ef54231a6144fcb04a764912651f015bc4/themes/dracula.json#L423-L826

Also wondering if we need to customize vim mode as `vim_mode_text` is removed: https://github.com/zed-industries/zed/pull/39813?  Thanks.
